//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_Persons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDetail
    {
        public int SaleDetailID { get; set; }
        public int SaleID { get; set; }
        public int RegionID { get; set; }
        public decimal Sell { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
